services:
  brw-tracker:
    build: .
    env_file:
      - .env
    image: brw-tracker:stable    
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brw-tracker-stable-db
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: